apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        imagePullPolicy: IfNotPresent
        image: jonathanwx/kubernetes-zookeeper:3.6.0
        ports:
          - containerPort: 2181
            name: port1
          - containerPort: 2888
            name: port2
          - containerPort: 3888
            name: port3
        env:
        - name: REPLICAS
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: port1
    targetPort: 2181
  - port: 2888
    name: port2
    targetPort: 2888
  - port: 3888
    name: port3
    targetPort: 3888
  clusterIP: None
  selector:
    app: zookeeper